- name: Connect to remote host via SSH
  hosts: all
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Create pandeeswari user
      user:
        name: pandeeswari
        shell: /bin/bash
        createhome: yes
