---
- hosts: "{{ host_group }}"
  remote_user: ubuntu
  become: yes
  tasks:
    - name: downloading tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.6/bin/apache-tomcat-10.1.6.tar.gz
        dest: /opt
    - name: extracting tomcat
      unarchive:
        src: /opt/apache-tomcat-10.1.6.tar.gz
        dest: /opt
        remote_src: yes
    - name: installing java
      yum:
        name: java-11-amazon-corretto
        state: present
    - name: copy jar file
      copy:
        src: /var/lib/jenkins/workspace/spring boot/target/springbootApp.jar
        dest: /opt/apache-tomcat-10.1.6/webapps/
    - name: starting tomcat
      shell: nohup /opt/apache-tomcat-10.1.6/bin/startup.sh &
